### ISSUE TITLE
Add ability to derive traits on the final state machine

### ISSUE THREAD

**Issue by maxwellodri** [mdeloof/statig#6]
Traits like Clone & serde's (De)serialize come to mind mostly. Something like the proc-macro generating the final state machine's struct directly could work? It'd be nice to have same ability to derive traits similar to deriving them on State/SuperState.

**Comment by mdeloof** [comment]
Yes, this definitely something that I'll be adding pretty soon. Thanks for bringing by it up!

**Comment by mdeloof** [comment]
This has been added in d71bd3d04bd0442750d237e9c71e5d11b0a71488. Serde's traits can be enabled with the `serde` features.
